services:
  code-runner:
    build:
      context: ./docker/code-runner
    image: java-runner
    container_name: java-runner-service-container

  python-runner-service:
    build:
      context: ./docker/python-runner
    image: python-runner
    container_name: python-runner-service-container
    # stdin_open, tty, volumes: Benzer şekilde, anlık container'lar için daha az relevant.

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always